version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: imba
    ports:
      - "0.0.0.0:5432:5432" # explicitly expose to all network interfaces. Expose PostgreSQL Publicly
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/etc/postgresql/custom-pg_hba.conf
      - ./config/postgresql.conf:/etc/postgresql/custom-postgresql.conf
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/data
    command: >
      postgres -c config_file=/etc/postgresql/custom-postgresql.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # username
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:
