AWSTemplateFormatVersion: "2010-09-09"
Description: Create AWS DMS tasks to split workload between large and small tables

Resources:
  ## Task 1: All tables except `order_products__prior`
  DmsTaskSmallTables:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationTaskIdentifier: dms-small-tables
      SourceEndpointArn: !ImportValue DmsPostgresSourceEndpoint
      TargetEndpointArn: !ImportValue DmsS3TargetEndpoint
      ReplicationInstanceArn: !ImportValue DmsReplicationInstance
      MigrationType: full-load
      TableMappings:
        Fn::Sub: |
          {
            "rules": [
              {
                "rule-type": "selection",
                "rule-id": "small-tables",
                "rule-name": "small-tables",
                "object-locator": {
                  "schema-name": "public",
                  "table-name": "^(?!order_products__prior$).*"
                },
                "rule-action": "include"
              }
            ]
          }
      ReplicationTaskSettings:
        Fn::Sub: |
          {
            "FullLoadSettings": {
              "MaxFullLoadSubTasks": 16,
              "TransactionConsistencyTimeout": 600,
              "CommitRate": 100000,
              "CreatePkAfterFullLoad": false,
              "TargetTablePrepMode": "DO_NOTHING"
            },
            "StreamBufferSettings": {
              "StreamBufferCount": 8,
              "StreamBufferSizeInMB": 32,
              "CtrlStreamBufferSizeInMB": 5
            },
            "ErrorBehavior": {
              "DataErrorPolicy": "LOG_ERROR",
              "FullLoadIgnoreConflicts": true,
              "RecoverableErrorCount": 5,
              "RecoverableErrorInterval": 5,
              "DataErrorEscalationPolicy": "SUSPEND_TABLE",
              "TableErrorPolicy": "SUSPEND_TABLE"
            },
            "Logging": {
              "EnableLogging": true,
              "LogComponents": [
                {"Id": "SOURCE_UNLOAD", "Severity": "LOGGER_SEVERITY_DEFAULT"},
                {"Id": "TARGET_LOAD", "Severity": "LOGGER_SEVERITY_DEFAULT"}
              ]
            },
            "ControlTablesSettings": {
              "historyTimeslotInMinutes": 5,
              "controlSchema": "dms_control",
              "HistoryTableEnabled": false,
              "StatusTableEnabled": false
            },
            "ValidationSettings": { "EnableValidation": false }
          }

  ## Task 2: Only `order_products__prior`
  DmsTaskLargeTable:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationTaskIdentifier: dms-large-table
      SourceEndpointArn: !ImportValue DmsPostgresSourceEndpoint
      TargetEndpointArn: !ImportValue DmsS3TargetEndpoint
      ReplicationInstanceArn: !ImportValue DmsReplicationInstance
      MigrationType: full-load
      TableMappings:
        Fn::Sub: |
          {
            "rules": [
              {
                "rule-type": "selection",
                "rule-id": "large-table",
                "rule-name": "large-table",
                "object-locator": {
                  "schema-name": "public",
                  "table-name": "order_products__prior"
                },
                "rule-action": "include"
              }
            ]
          }
      ReplicationTaskSettings:
        Fn::Sub: |
          {
            "FullLoadSettings": {
              "MaxFullLoadSubTasks": 16,
              "TransactionConsistencyTimeout": 600,
              "CommitRate": 100000,
              "CreatePkAfterFullLoad": false,
              "TargetTablePrepMode": "DO_NOTHING"
            },
            "StreamBufferSettings": {
              "StreamBufferCount": 8,
              "StreamBufferSizeInMB": 32,
              "CtrlStreamBufferSizeInMB": 5
            },
            "ErrorBehavior": {
              "DataErrorPolicy": "LOG_ERROR",
              "FullLoadIgnoreConflicts": true,
              "RecoverableErrorCount": 5,
              "RecoverableErrorInterval": 5,
              "DataErrorEscalationPolicy": "SUSPEND_TABLE",
              "TableErrorPolicy": "SUSPEND_TABLE"
            },
            "Logging": {
              "EnableLogging": true,
              "LogComponents": [
                {"Id": "SOURCE_UNLOAD", "Severity": "LOGGER_SEVERITY_DEFAULT"},
                {"Id": "TARGET_LOAD", "Severity": "LOGGER_SEVERITY_DEFAULT"}
              ]
            },
            "ControlTablesSettings": {
              "historyTimeslotInMinutes": 5,
              "controlSchema": "dms_control",
              "HistoryTableEnabled": false,
              "StatusTableEnabled": false
            },
            "ValidationSettings": { "EnableValidation": false }
          }

Outputs:
  DmsTaskSmallTablesArn:
    Description: DMS Task for small tables
    Value: !Ref DmsTaskSmallTables
    Export:
      Name: DmsTaskSmallTablesArn

  DmsTaskLargeTableArn:
    Description: DMS Task for the large table
    Value: !Ref DmsTaskLargeTable
    Export:
      Name: DmsTaskLargeTableArn
