AWSTemplateFormatVersion: "2010-09-09"
Description: Create AWS DMS source (PostgreSQL), target (S3) endpoints, AWS DMS Replication Instance

Parameters:
  PostgreSQLSecret:
    Type: String
    Description: PostgreSQL Credential Name in Secret Manager
    Default: postgresql_dms
  SourceBucketName:
    Description: Name the source Bucket
    Type: String

Resources:
  ## DMS S3 Target Endpoint ##
  DmsS3TargetEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: dms-s3-target
      EndpointType: target
      EngineName: s3
      S3Settings:
        BucketName: !Ref SourceBucketName
        BucketFolder: dms-input
        CompressionType: GZIP
        CsvDelimiter: ","
        CsvRowDelimiter: "\n"
        DataFormat: csv
        EnableStatistics: false
        MaxFileSize: 65536 # ~64MB per file
        DatePartitionEnabled: false
        ServiceAccessRoleArn: !ImportValue EMRDMSGlueExecutionRoleArn

  ## DMS PostgreSQL Source Endpoint using Secrets Manager ##
  DmsPostgresSourceEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: postgresql-local-macbook
      EndpointType: source
      EngineName: postgres
      DatabaseName: imba
      SslMode: none
      PostgreSqlSettings:
        SecretsManagerSecretId: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${PostgreSQLSecret}
        SecretsManagerAccessRoleArn: !ImportValue EMRDMSGlueExecutionRoleArn

  DmsReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupIdentifier: dms-subnet-group
      ReplicationSubnetGroupDescription: Subnet group for DMS replication instance
      SubnetIds:
        - !ImportValue Shared-PrivateSubnet1Id
        - !ImportValue Shared-PrivateSubnet2Id

  DMSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DMS access to PostgreSQL
      VpcId: !ImportValue Shared-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
          Description: PostgreSQL access from external source
      Tags:
        - Key: Name
          Value: DMSSecurityGroup

  ## DMS Replication Instance ##
  DmsReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    DependsOn:
      - DmsReplicationSubnetGroup
      - DMSSecurityGroup
    Properties:
      ReplicationInstanceIdentifier: dms-replication-instance
      ReplicationInstanceClass: dms.c5.xlarge
      EngineVersion: 3.6.0
      AllocatedStorage: 100
      VpcSecurityGroupIds:
        - !Ref DMSSecurityGroup
      ReplicationSubnetGroupIdentifier: !Ref DmsReplicationSubnetGroup
      PubliclyAccessible: true
      AutoMinorVersionUpgrade: true
      MultiAZ: false
      Tags:
        - Key: Name
          Value: dms-replication-instance

Outputs:
  DmsReplicationInstance:
    Value: !Ref DmsReplicationInstance
    Export:
      Name: DmsReplicationInstance

  DmsPostgresSourceEndpoint:
    Value: !Ref DmsPostgresSourceEndpoint
    Export:
      Name: DmsPostgresSourceEndpoint

  DmsS3TargetEndpoint:
    Value: !Ref DmsS3TargetEndpoint
    Export:
      Name: DmsS3TargetEndpoint
