AWSTemplateFormatVersion: "2010-09-09"
Description: Create EMR Cluster and run script

Parameters:
  ClusterName:
    Type: String
    Default: my-emr-cluster
  SourceBucketName:
    Description: Name the source or script Bucket
    Type: String

Resources:
  EMRServiceRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: EMR-Service-Role
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: elasticmapreduce.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole
    Tags:
      - Key: Name
        Value: EMRServiceRole

  # Instance Profile for EMR EC2 instances
  EMRDMSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EMRDMSInstanceProfile
      Roles:
        - !ImportValue EMRDMSGlueExecutionRoleName

  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: !Ref ClusterName
      ReleaseLabel: emr-7.6.0
      Applications:
        - Name: Spark
        - Name: Hive
      Instances:
        Ec2KeyName: Macbook
        Ec2SubnetId: !ImportValue Shared-PrivateSubnet1Id
        KeepJobFlowAliveWhenNoSteps: false
        TerminationProtected: false
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m4.large
          Market: ON_DEMAND
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: m4.large
          Market: ON_DEMAND
      JobFlowRole: !Ref EMRDMSInstanceProfile
      ServiceRole: !Ref EMRServiceRole
      VisibleToAllUsers: true # Makes the cluster visible to all IAM users in the account.
      LogUri: !Sub s3://${SourceBucketName}/emr/ # Stores job logs (stdout, stderr, and step logs) in S3.
      Configurations:
        - Classification: hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
        - Classification: spark-hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
      Steps:
        - Name: Run PySpark Script
          ActionOnFailure: CANCEL_AND_WAIT # or CONTINUE
          HadoopJarStep:
            Jar: command-runner.jar
            Args:
              - spark-submit
              - !Sub s3://${SourceBucketName}/scripts/features.py # replace with your script path

Outputs:
  ClusterId:
    Description: EMR Cluster ID
    Value: !Ref EMRCluster
