AWSTemplateFormatVersion: "2010-09-09"
Description: Create EMR Cluster and run script

Parameters:
  ClusterName:
    Type: String
    Default: my-emr-cluster
  SourceBucketName:
    Description: Name the source or script Bucket
    Type: String

Resources:
  # Instance Profile for EMR EC2 instances
  EMRDMSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EMRDMSInstanceProfile
      Roles:
        - !ImportValue EMRDMSGlueExecutionRoleName

  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: !Ref ClusterName
      ReleaseLabel: emr-6.15.0
      Applications:
        - Name: Spark
        - Name: Hive
      Instances:
        Ec2KeyName: Macbook
        Ec2SubnetId: !ImportValue Shared-PrivateSubnet1Id
        KeepJobFlowAliveWhenNoSteps: false
        TerminationProtected: false
        InstanceGroups:
          - InstanceRole: MASTER
            InstanceType: m5.large
            InstanceCount: 1
            Market: ON_DEMAND
          - InstanceRole: CORE
            InstanceType: m5.large
            InstanceCount: 2
            Market: ON_DEMAND
      JobFlowRole: !Ref EMRDMSInstanceProfile
      ServiceRole: !ImportValue EMRDMSGlueExecutionRoleArn
      VisibleToAllUsers: true # Makes the cluster visible to all IAM users in the account.
      LogUri: !Sub s3://${SourceBucketName}/emr/ # Stores job logs (stdout, stderr, and step logs) in S3.
      Configurations:
        - Classification: hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
        - Classification: spark-hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
      Steps:
        - Name: Run PySpark Script
          ActionOnFailure: TERMINATE_CLUSTER
          HadoopJarStep:
            Jar: command-runner.jar
            Args:
              - spark-submit
              - !Sub s3://${SourceBucketName}/scripts/features.py # replace with your script path

Outputs:
  ClusterId:
    Description: EMR Cluster ID
    Value: !Ref EMRCluster
