Parameters:
  PostgreSQLSecret:
    Type: String
    Description: PostgreSQL Credential Name in Secret Manager
    Default: postgresql_dms

Resources:
  EMRDMSGlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EMR-DMS-Glue-ExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub elasticmapreduce.${AWS::Region}.amazonaws.com
                - !Sub dms.${AWS::Region}.amazonaws.com
                - !Sub glue.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess # Access to S3 (e.g., logs, data)
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess # Full Glue service access
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole # Required for Glue jobs
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole # Needed by DMS
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole # EMR core service role
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess # Log writing access
      Policies:
        - PolicyName: CustomSecretAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${PostgreSQLSecret}-*
      Tags:
        - Key: Name
          Value: EMR-DMS-Glue-ExecutionRole
Outputs:
  EMRDMSGlueExecutionRoleArn:
    Description: ARN of EMR-DMS-Glue Execution Role
    Value: !GetAtt EMRDMSGlueExecutionRole.Arn
    Export:
      Name: EMRDMSGlueExecutionRoleArn
