name: Deploy EMR cluster and run step

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "ap-southeast-2"
      SourceBucketName:
        description: "S3 Source Bucket Name"
        default: "source-bucket-chien"
        required: true
      DataBucketName:
        description: "S3 Data Bucket Name"
        default: "data-bucket-chien"
        required: true

jobs:
  emr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Deploy Glue tables
        id: glue-tables
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: glue-tables
          template: cfn/glue-tables.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            DataBucket=SourceBucketName=${{ github.event.inputs.SourceBucketName }},
            DataFolder=dms-input,
            DatabasesName=imba-raw

      - name: Upload Spark Script
        run: |
          aws s3 cp scripts/ s3://${{ github.event.inputs.SourceBucketName }}/scripts/ --recursive
      - name: Set today's date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Deploy EMR spark job
        id: emr-spark
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: emr-spark
          template: cfn/emr.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            ClusterName=emr-cluster-${{ env.TODAY }},
            SourceBucketName=${{ github.event.inputs.SourceBucketName }}
